#Hugo configuration
title = "13sdfd"
baseURL = "https:\/\/342w4rsdf.sdf.svd"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758823"
subfolder = ""
